Handle literal_column() in ExcludeConstraint differently
Before the change, a literal_column in an ExcludeConstraint ended up as a `column("...")`which in turn meant that the actual migration errored with

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "id + 2" named in key does not exist

[SQL:
CREATE TABLE whatever2 (
        id BIGSERIAL NOT NULL,
        PRIMARY KEY (id),
        CONSTRAINT whatever_id_int8range_excl EXCLUDE USING gist (id WITH =, "id + 2" WITH =)
)
```

Note: the column name is interpreted as a quoted column named "id + 2".

After the fix, a literal_column is passed through, ending up in the correct SQL, which can be run on PG.